config/routes.rb
Rails.application.routes.draw do

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

  mount Decidim::Core::Engine => '/'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end
# Agreagamos las rutas de nav a las rutas de decidim Admin
Decidim::Admin::Engine.routes.draw do
  constraints(->(request) { Decidim::Admin::OrganizationDashboardConstraint.new(request).matches? }) do
    resources :navs
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/nav.rb
class Nav < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/decidim/admin/navs_controller.rb
module Decidim
  module Admin
      class NavsController < Decidim::Admin::ApplicationController
        before_action :set_nav, only: [:show, :edit, :update, :destroy]

        # GET /navs
        def index
          @navs = Nav.all
        end

        # GET /navs/1
        def show
        end

        # GET /navs/new
        def new
          @nav = Nav.new
        end

        # GET /navs/1/edit
        def edit
        end

        # POST /navs
        def create
          @nav = Nav.new(nav_params)

          if @nav.save
            redirect_to @nav, notice: 'Nav was successfully created.'
          else
            render :new
          end
        end

        # PATCH/PUT /navs/1
        def update
          if @nav.update(nav_params)
            redirect_to @nav, notice: 'Nav was successfully updated.'
          else
            render :edit
          end
        end

        # DELETE /navs/1
        def destroy
          @nav.destroy
          redirect_to navs_url, notice: 'Nav was successfully destroyed.'
        end

        private
          # Use callbacks to share common setup or constraints between actions.
          def set_nav
            @nav = Nav.find(params[:id])
          end

          # Only allow a list of trusted parameters through.
          def nav_params
            params.require(:nav).permit(:laber, :url)
          end
       end
    end
end

app/controllers/decidim_controller.rb
# Entry point for Decidim. It will use the `DecidimController` as
# entry point, but you can change what controller it inherits from
# so you can customize some methods.
class DecidimController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/decidim/menu_helper.rb
# frozen_string_literal: true

module Decidim
  # This module includes helpers to manage menus in layout
  module MenuHelper
    # Public: Returns the main menu presenter object
    def main_menu
      Nav.all
    end
    # def main_menu
    #   @main_menu ||= ::Decidim::MenuPresenter.new(
    #     :menu,
    #     self,
    #     element_class: "main-nav__link",
    #     active_class: "main-nav__link--active",
    #     label: t("layouts.decidim.header.main_menu")
    #   )
    # end

    # Public: Returns the user menu presenter object
    def user_menu
      @user_menu ||= ::Decidim::InlineMenuPresenter.new(
        :user_menu,
        self,
        element_class: "tabs-title",
        active_class: "is-active",
        label: t("layouts.decidim.user_menu.title")
      )
    end
  end
end

app/helpers/navs_helper.rb
module NavsHelper
end

app/views/admin/partials/_main_nav.html.erb
<div class="main-nav">
  <ul>
    <li>d</li>
  </ul>
</div>

app/views/decidim/admin/navs/_form.html.erb
<%= form_with(model: nav) do |form| %>
  <% if nav.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(nav.errors.count, "error") %> prohibited this nav from being saved:</h2>

      <ul>
        <% nav.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.text_field :laber %>
  </div>

  <div class="field">
    <%= form.text_field :url %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/decidim/admin/navs/edit.html.erb
<div class="container">
  <div class="process-title">
    <div class="process-title-content">
      <a href="admin/navs">Navbars</a>
    </div>
  </div>
  <div class="process-content">
    <div class="card with-overflow">
      <div class="card-divider">
        <h2 class="card-title">Editar Navbar
          <%= link_to 'Mostrar', @nav, class:"button tiny button--title" %>
          <%= link_to 'Volver', navs_path, class:"button tiny button--title" %>
        </h2>
      </div>
      <div class="card-section">
      <%= render 'form', nav: @nav %>
      </div>
    </div>
  </div>
</div>

app/views/decidim/admin/navs/index.html.erb
<p id="notice"><%= notice %></p>
<div class="container">
  <div class="process-title">
    <div class="process-title-content">
      <a href="admin/navs">Navbars</a>
    </div>
  </div>
  <div class="process-content">
    <div class="card with-overflow">
      <div class="card-divider">
        <h2 class="card-title">Navbars
          <%= link_to 'Crear Nav', new_nav_path, class:"button tiny button--title" %>
        </h2>
      </div>
      <div class="card-section">
        <div class="table-scroll">
          <table class="table-list">
            <thead>
              <tr>
                <th>Laber</th>
                <th>Url</th>
                <th colspan="3"></th>
              </tr>
            </thead>

            <tbody>
              <% @navs.each do |nav| %>
                <tr>
                  <td><%= nav.laber %></td>
                  <td><%= nav.url %></td>
                  <td class="table-list__actions">
                    <%= icon_link_to "eye", nav, t("actions.preview", scope: "decidim.admin"), class: "action-icon--preview", target: :blank %>
                    <%= icon_link_to "pencil", [:edit, nav], t("actions.edit", scope: "decidim.admin"), class: "action-icon--edit", method: :get, data: {} %>
                    <%= icon_link_to "circle-x", nav, t("actions.destroy", scope: "decidim.admin"), class: "action-icon--remove", method: :delete, data: { confirm: t("actions.confirm_destroy", scope: "decidim.admin") } %>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/decidim/admin/navs/new.html.erb
<div class="container">
  <div class="process-title">
    <div class="process-title-content">
      <a href="admin/navs">Navbars</a>
    </div>
  </div>
  <div class="process-content">
    <div class="card with-overflow">
      <div class="card-divider">
        <h2 class="card-title">Nuevo Navbar
          <%= link_to 'Volver', navs_path, class:"button tiny button--title" %>
        </h2>
      </div>
      <div class="card-section">
      <%= render 'form', nav: @nav %>
      </div>
    </div>
  </div>
</div>

app/views/decidim/admin/navs/show.html.erb
<div class="container">
  <div class="process-title">
    <div class="process-title-content">
      <a href="admin/navs">Navbars</a>
    </div>
  </div>
  <div class="process-content">
    <div class="card with-overflow">
      <div class="card-divider">
        <h2 class="card-title">Navbar
          <%= link_to 'Editar', edit_nav_path(@nav), class:"button tiny button--title" %>
          <%= link_to 'Atras', navs_path, class:"button tiny button--title" %>
        </h2>
      </div>
      <div class="card-section">
        <p id="notice"><%= notice %></p>

        <p>
          <strong>Laber:</strong>
          <%= @nav.laber %>
        </p>

        <p>
          <strong>Url:</strong>
          <%= @nav.url %>
        </p>

      </div>
    </div>
  </div>
</div>

app/views/layouts/decidim/_navadmin.html.erb
<div class="layout-nav">
      <nav class="main-nav" aria-label="Menú principal">
        <ul>
          <li><a href="/admin/navs" data-accessibility-violation="true"><svg aria-label="dashboard" role="img" aria-hidden="true" class="icon--dashboard icon"><title>dashboard</title><use href="/decidim-packs/media/images/icons-c4fd0f43651700b0c768.svg#icon-dashboard"></use></svg>Gestionar menu</a>
          </li>
          <li>
            <a href="/admin/"><svg aria-label="dashboard" role="img" aria-hidden="true" class="icon--dashboard icon"><title>dashboard</title><use href="/decidim-packs/media/images/icons-c4fd0f43651700b0c768.svg#icon-dashboard"></use></svg>Panel de control</a>
          </li>
          <li><a href="/admin/participatory_processes"><svg aria-label="target" role="img" aria-hidden="true" class="icon--target icon"><title>target</title><use href="/decidim-packs/media/images/icons-c4fd0f43651700b0c768.svg#icon-target"></use></svg>Procesos</a>
          </li>
          <li><a href="/admin/assemblies"><svg aria-label="dial" role="img" aria-hidden="true" class="icon--dial icon"><title>dial</title><use href="/decidim-packs/media/images/icons-c4fd0f43651700b0c768.svg#icon-dial"></use></svg>Asambleas</a>
          </li>
          <li><a href="/admin/moderations"><svg aria-label="flag" role="img" aria-hidden="true" class="icon--flag icon"><title>flag</title><use href="/decidim-packs/media/images/icons-c4fd0f43651700b0c768.svg#icon-flag"></use></svg>Moderaciones globales</a>
          </li>
          <li><a href="/admin/static_pages"><svg aria-label="book" role="img" aria-hidden="true" class="icon--book icon"><title>book</title><use href="/decidim-packs/media/images/icons-c4fd0f43651700b0c768.svg#icon-book"></use></svg>Páginas</a>
          </li>
          <li><a href="/admin/users"><svg aria-label="person" role="img" aria-hidden="true" class="icon--person icon"><title>person</title><use href="/decidim-packs/media/images/icons-c4fd0f43651700b0c768.svg#icon-person"></use></svg>Participantes</a>
          </li>
          <li><a href="/admin/newsletters"><svg aria-label="envelope-closed" role="img" aria-hidden="true" class="icon--envelope-closed icon"><title>envelope-closed</title><use href="/decidim-packs/media/images/icons-c4fd0f43651700b0c768.svg#icon-envelope-closed"></use></svg>Boletines</a>
          </li>
          <li><a href="/admin/organization/edit"><svg aria-label="wrench" role="img" aria-hidden="true" class="icon--wrench icon"><title>wrench</title><use href="/decidim-packs/media/images/icons-c4fd0f43651700b0c768.svg#icon-wrench"></use></svg>Configuración</a>
          </li>
          <li><a href="/admin/logs" data-accessibility-violation="true"><svg aria-label="dashboard" role="img" aria-hidden="true" class="icon--dashboard icon"><title>dashboard</title><use href="/decidim-packs/media/images/icons-c4fd0f43651700b0c768.svg#icon-dashboard"></use></svg>Registro de actividad de administración</a></li></ul>
      </nav>
    </div>

app/views/layouts/decidim/_nuevo_nav.html.erb
<nav class="main-nav">
  <ul>
  <% main_menu.each do |menu| %>
    <li class="main-nav__link">
      <a href="<%= menu.url %>">
        <%= menu.laber %>
      </a>
    </li>
  <% end %>
  </ul>
</nav>

app/views/layouts/decidim/_wrapper.html.erb
<%
if respond_to?(:current_component) && current_component && can_be_managed?(current_component)
  edit_link(
    manage_component_path(current_component),
    :read,
    :component,
    component: current_component,
    current_participatory_space: current_participatory_space
  )
end
%>

<!-- REDESIGN_PENDING: Remove when redesigned is finished -->
<div class="off-canvas-wrapper">
  <div class="off-canvas-wrapper-inner" data-off-canvas-wrapper>
    <div class="off-canvas position-right hide-for-large" data-position="right"
         id="offCanvas" data-off-canvas>
      <!-- Close button -->
      <button class="close-button"
              aria-label="<%= t("layouts.decidim.header.close_menu") %>" type="button"
              data-close>
        <span aria-hidden="true">&times;</span>
      </button>
      <!-- Menu -->
      <div class="hide-for-medium" data-set="nav-holder"></div>
      <div class="hide-for-medium usermenu-off-canvas-holder"
           data-set="nav-login-holder"></div>
      <div class="hide-for-medium mt-s ml-s mr-s search-off-canvas-holder"
           data-set="nav-search-holder"></div>
    </div>
    <div class="off-canvas-content" data-off-canvas-content>
      <div class="footer-separator">
        <!--separates the footer from the rest of the page,
             creates a sticky footer-->
        <div class="header" role="banner">
          <!-- Topbar -->
          <div class="title-bar">
            <%= link_to t("skip_button", scope: "decidim.accessibility"), url_for(anchor: "content"), class: "skip" %>
            <% if current_organization.official_img_header.attached? %>
              <%= link_to  current_organization.official_url, class: "logo-cityhall" do %>
                <%= image_tag current_organization.attached_uploader(:official_img_header).path, alt: current_organization.name %>
              <% end %>
            <% end %>
            <div class="row column topbar">
              <div class="logo-wrapper">
                <%= render partial: "layouts/decidim/logo", locals: { organization: current_organization } %>
              </div>
              <%= render partial: "layouts/decidim/topbar_search" %>
              <%= render partial: "layouts/decidim/language_chooser" %>
              <div class="hide-for-medium topbar__menu">
                <button type="button" data-toggle="offCanvas" aria-label="<%= t("layouts.decidim.header.navigation") %>">
                  <%= icon "menu", aria_label: t("layouts.decidim.header.navigation"), role: "img" %>
                </button>
              </div>
              <% if current_user %>
                <nav class="topbar__dropmenu topbar__user__logged" aria-label="<%= t("layouts.decidim.header.user_menu") %>">
                  <%= link_to decidim.notifications_path, class: "topbar__notifications #{current_user.notifications.any? ? "is-active" : ""}" do %>
                    <%= icon "bell", role: "img", aria_label: t("layouts.decidim.user_menu.notifications") %>
                  <% end %>
                  <%= link_to decidim.conversations_path, class: "topbar__conversations #{current_user.unread_conversations.any? ? "is-active" : ""}" do %>
                    <%= icon "envelope-closed", role: "img", aria_label: t("layouts.decidim.user_menu.conversations") %>
                  <% end %>
                  <ul class="dropdown menu" data-dropdown-menu
                    data-autoclose="false"
                    data-disable-hover="true"
                    data-click-open="true"
                    data-close-on-click="true"
                    role="menubar">
                    <li class="is-dropdown-submenu-parent show-for-medium" role="presentation">
                      <%= link_to current_user.name, decidim.account_path, id: "user-menu-control", "aria-controls": "user-menu", "aria-haspopup": "menu", "aria-label": t("layouts.decidim.user_menu.account", name: current_user.name), "role": "menuitem" %>
                      <ul class="menu is-dropdown-submenu" id="user-menu" role="menu" aria-labelledby="user-menu-control">
                        <%= render partial: "layouts/decidim/user_menu" %>
                      </ul>
                      <div data-set="nav-login-holder" class="show-for-medium">
                        <!-- Repeated due to dropdown limitations -->
                        <ul class="menu is-dropdown-submenu js-append usermenu-off-canvas">
                          <%= render partial: "layouts/decidim/user_menu" %>
                        </ul>
                      </div>
                    </li>
                  </ul>
                </nav>
              <% else %>
                <div class="topbar__user show-for-medium" data-set="nav-login-holder">
                  <div class="topbar__user__login js-append">
                    <% if current_organization.sign_up_enabled? %>
                      <%= link_to t("layouts.decidim.header.sign_up"), decidim.new_user_registration_path, class: "sign-up-link" %>
                    <% end %>
                    <%= link_to t("layouts.decidim.header.sign_in"), decidim.new_user_session_path, class: "sign-in-link" %>
                  </div>
                </div>
              <% end %>

              <%= render partial: "layouts/decidim/admin_links" %>
            </div>
          </div>
          <div class="show-for-medium" data-set="nav-holder">
            <div class="navbar js-append" style="background: #404052 !important;">
              <div class="row column">
                <%= render partial: "layouts/decidim/nuevo_nav" %>
              </div>
            </div>
          </div>
        </div>

        <main id="content" data-content>
          <%= display_flash_messages %>
          <%= yield %>
        </main>
      </div>
      <div class="footer" role="contentinfo">
        <%= render partial: "layouts/decidim/main_footer" %>
        <%= render partial: "layouts/decidim/mini_footer" %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/decidim/admin/_application.html.erb
<% add_decidim_page_title(t("titles.panel", scope: "decidim.admin")) %>
<% add_decidim_page_title(current_organization.name) %>
<!doctype html>
<html class="no-js" lang="<%= I18n.locale %>">
  <head>
    <meta charset="utf-8">
    <meta content="IE=edge,chrome=1" http-equiv="X-UA-Compatible">
    <meta name="author" content="">
    <meta name="copyright" content="">
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= decidim_page_title %></title>
    <%= render partial: "layouts/decidim/admin/header" %>
  </head>
  <body>
    <%= render partial: "layouts/decidim/timeout_modal" %>
    <%= render partial: "layouts/decidim/admin/template_top" %>
    <div class="layout-nav">
        <%= render partial: "layouts/decidim/navadmin" %>
      <!-- <div class="layout-wrapper">
        <nav class="main-nav">
          <ul>
            <li><a href="/admin/navs" data-accessibility-violation="true"><svg aria-label="dashboard" role="img" aria-hidden="true" class="icon--dashboard icon"><title>dashboard</title><use href="/decidim-packs/media/images/icons-c4fd0f43651700b0c768.svg#icon-dashboard"></use></svg>Gestionar menu</a>
            </li>
          </ul>
        </nav>
      </div> -->
      <%= yield :secondary_nav if content_for? :secondary_nav %>
      <%= yield :sidebar_menu_nav if content_for? :sidebar_menu_nav %>
    </div>
    <div class="layout-content">
      <div class="container">
        <%= yield %>
      </div>
    </div>
    <%= render partial: "layouts/decidim/admin/template_bottom" %>
    <%= render partial: "decidim/shared/confirm_modal" %>
    <%= render partial: "layouts/decidim/admin/js_configuration" %>
    <%= render partial: "layouts/decidim/cors" if Decidim.cors_enabled %>

    <%= snippets.display(:foot) %>
  </body>
</html>

app/views/layouts/decidim/footer/_redesigned_main.html.erb
<div class="bg-gray-4">
  <div class="flex flex-col lg:flex-row gap-8 container py-10">
    <div class="lg:w-1/3">
      <%= render partial: "layouts/decidim/footer/redesigned_main_intro" %>
    </div>
    <div class="lg:w-2/3 grid grid-cols-2 gap-x-4 gap-y-10 lg:grid-cols-4 text-md text-white">
      <%= render partial: "layouts/decidim/footer/redesigned_main_links" %>
    </div>
  </div>
  <div class="border-t border-black flex flex-wrap items-center gap-6 container py-6 text-white">
    <nav class="md:w-1/2 lg:w-auto" role="navigation" aria-label="Legal">
      <%= render partial: "layouts/decidim/footer/redesigned_main_legal" %>
    </nav>
    <nav class="max-w-fit w-full md:w-auto md:ml-auto" role="navigation" aria-label="Social media">
      <%= render partial: "layouts/decidim/footer/redesigned_main_social_media_links" %>
    </nav>
    <%= render partial: "layouts/decidim/footer/redesigned_main_language_chooser" %>
  </div>
</div>

app/views/layouts/decidim/footer/_redesigned_main_intro.html.erb
<% if current_organization.official_img_footer.attached? %>
  <%= link_to current_organization.official_url, class: "block mb-6" do %>
    <%= image_tag current_organization.attached_uploader(:official_img_footer).path, alt: current_organization.name, class: "max-h-16" %>
  <% end %>
<% end %>
<div class="text-sm text-white prose">
  <p><%= t("decidim.pages.home.footer_sub_hero.footer_sub_hero_headline", organization: current_organization.name) %></p>
  <p><%== t("decidim.pages.home.footer_sub_hero.footer_sub_hero_body") %></p>
</div>

app/views/layouts/decidim/footer/_redesigned_main_language_chooser.html.erb
<% if available_locales.length> 1 %>
  <details class="relative">
    <summary id="language-chooser-control"
      class="flex items-center border border-white rounded py-1.5 px-2 cursor-pointer text-md font-semibold"
      aria-controls="language-chooser-menu">
      <%= icon "global-line" , class: "w-4 h-4 fill-current" %>
      <span class="ml-1">
        <%= t("name", scope: "locale" ) %>
      </span>
      <%= icon "arrow-down-s-line" , class: "w-4 h-4 ml-4 fill-current" %>
      <span class="sr-only">
        <% available_locales.each do |locale| %>
          <span lang="<%= locale %>">
            <%= I18n.with_locale(locale) { t("layouts.decidim.language_chooser.choose_language") } %>
          </span>
        <% end %>
      </span>
    </summary>

    <ul id="language-chooser-menu" class="absolute top-full left-0 bg-white rounded w-full" role="menu"
      aria-labelledby="language-chooser-control">
      <% (available_locales - [I18n.locale.to_s]).each do |locale| %>
        <li class="text-black text-md hover:bg-secondary hover:text-white transition" role="presentation">
          <%= link_to locale_name(locale), decidim.locale_path(locale: locale), method: :post, role: "menuitem", lang: locale, class: "p-2 w-full block" %>
        </li>
        <% end %>
    </ul>
  </details>
<% end %>

app/views/layouts/decidim/footer/_redesigned_main_legal.html.erb
<ul class="flex flex-col md:flex-row gap-10 text-sm text-white">
  <li>
    <%= link_to "Avís Legal" %>
  </li>
  <li>
    <%= link_to "Termes i condicions d'ús" %>
  </li>
  <li>
    <%= link_to "Cookies" %>
  </li>
</ul>

app/views/layouts/decidim/footer/_redesigned_main_links.html.erb
<nav role="navigation" aria-label="Decidim">
  <h2 class="h5 mb-4">Decidim</h2>
  <ul class="space-y-4 break-inside-avoid">
     <li class="font-semibold"><%= link_to "Processos" %></li>
     <li class="font-semibold"><%= link_to "Assemblees" %></li>
     <li class="font-semibold"><%= link_to "Iniciativas" %></li>
     <li class="font-semibold"><%= link_to "Votacions" %></li>
     <li class="font-semibold"><%= link_to "Consultes" %></li>
     <li class="font-semibold"><%= link_to "Jornades" %></li>
  </ul>
</nav>
<nav role="navigation" aria-label="Recursos">
  <h2 class="h5 mb-4">Recursos</h2>
  <ul class="space-y-4 break-inside-avoid">
     <li class="font-semibold"><%= link_to "Activitat" %></li>
     <li class="font-semibold"><%= link_to "Trobades" %></li>
  </ul>
</nav>
<nav role="navigation" aria-label="Interaccions">
  <h2 class="h5 mb-4">Interaccions</h2>
  <ul class="space-y-4 break-inside-avoid">
     <li class="font-semibold"><%= link_to "Ajuda general" %></li>
     <li class="font-semibold"><%= link_to "Preguntes freqüents" %></li>
     <li class="font-semibold"><%= link_to "Tutorials de participació" %></li>
     <li class="font-semibold"><%= link_to "Accesibilitat" %></li>
     <li class="font-semibold"><%= link_to "Dades obertes" %></li>
  </ul>
</nav>
<nav role="navigation" aria-label="El meu compte">
  <h2 class="h5 mb-4">El meu compte</h2>
  <ul class="space-y-4 break-inside-avoid">
     <li class="font-semibold"><%= link_to "Configuració" %></li>
     <li class="font-semibold"><%= link_to "Perfil públic" %></li>
     <li class="font-semibold"><%= link_to "Notificacions" %></li>
     <li class="font-semibold"><%= link_to "Converses" %></li>
  </ul>
</nav>

app/views/layouts/decidim/footer/_redesigned_main_social_media_links.html.erb
<ul class="flex justify-between md:justify-start gap-6 text-sm text-white">
Esto es un modificación
</ul>

app/views/layouts/decidim/footer/_redesigned_mini.html.erb
<div class="bg-black py-5">
  <div class="container flex justify-between items-center text-white">
    <div>
      <a rel="decidim noopener noreferrer" href="https://decidim.org/" target="_blank" data-external-link="false">
        <%= image_pack_tag("media/images/decidim-logo.svg", alt: t("layouts.decidim.footer.decidim_logo"), class: "max-h-8 block") %>
      </a>
      <div class="text-xs mt-2">
        <%= t("layouts.decidim.footer.made_with_open_source").html_safe %>
      </div>
    </div>
    <a class="flex gap-1" rel="license noopener noreferrer" href="http://creativecommons.org/licenses/by-sa/4.0/" target="_blank" data-external-link="false">
      <span class="sr-only">t("layouts.decidim.footer.cc_by_license")</span>
      <%= icon "creative-commons-line", class: "w-6 h-6 fill-current" %>
      <%= icon "creative-commons-by-line", class: "w-6 h-6 fill-current" %>
      <%= icon "creative-commons-sa-line", class: "w-6 h-6 fill-current" %>
    </a>
  </div>
</div>

app/views/navs/_form.html.erb
<%= form_with(model: nav) do |form| %>
  <% if nav.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(nav.errors.count, "error") %> prohibited this nav from being saved:</h2>

      <ul>
        <% nav.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :laber %>
    <%= form.text_field :laber %>
  </div>

  <div class="field">
    <%= form.label :url %>
    <%= form.text_field :url %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>